### ISSUE TITLE
core: Crash in FM code when unbinding and binding the same SLD device from the UI

### ISSUE THREAD

**Issue by kyeyoon-eeum** [opencxl/opencxl#130]
Crash in FM code when unbinding and binding the device again.
1. `./cxl-util start -c fm -c switch -c sld-group -c host-group --config-file configs/1vcs_4sld.yaml`
2. Unbind `vPPB 0` from `PPB 1`.
3. Try to bind `vPPB 0` to `PPB 1`
4. Crash with the following error.
```
[CxlRootPortDevice:Port0] HDM Decoder 3, HPA Size: 0x10000000
[CxlRootPortDevice:Port0] Waiting for a new action
[CxlVirtualSwitch 0] Started unbinding physical port from vPPB 0
[DownstreamPortDevice:DSP1] Unbinding ld_id 0 to vPPB-1 (noop)
VPPB unbinded from physical port, type: CXL_COMPONENT_TYPE.DSP
[CxlVirtualSwitch 0] Succcessfully unbound physical port from vPPB 0


Task exception was never retrieved
future: <Task finished name='Task-3666' coro=<AsyncServer._handle_event_internal() done, defined at /home/kyeyoon/.cache/pypoetry/virtualenvs/opencxl-dEamNF91-py3.11/lib/python3.11/site-packages/socketio/async_server.py:608> exception=KeyError('ldId')>
Traceback (most recent call last):
  File "/home/kyeyoon/.cache/pypoetry/virtualenvs/opencxl-dEamNF91-py3.11/lib/python3.11/site-packages/socketio/async_server.py", line 610, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyeyoon/.cache/pypoetry/virtualenvs/opencxl-dEamNF91-py3.11/lib/python3.11/site-packages/socketio/async_server.py", line 637, in _trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/kyeyoon/eeum-dev/my-opencxl-core/opencxl/cxl/component/fabric_manager/socketio_server.py", line 88, in _handle_event
    response = await self._bind_vppb(data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyeyoon/eeum-dev/my-opencxl-core/opencxl/cxl/component/fabric_manager/socketio_server.py", line 137, in _bind_vppb
    ld_id=data["ldId"],
          ~~~~^^^^^^^^
KeyError: 'ldId'
^\./cxl-util: line 2:  9127 Quit                    (core dumped) poetry run python opencxl/bin/cli.py "$@"
```

**Comment by arter97** [comment]
Was this after commit f70f90f578574d8c8a8d0984e9ef11fcc562f978? We're unable to reproduce this.

**Comment by kyeyoon-eeum** [comment]
> Was this after commit f70f90f578574d8c8a8d0984e9ef11fcc562f978? We're unable to reproduce this.

This can be reproduced with ToT `v0.4-dev` (303227c) + ToT  `jaekim/renewal` (f44a19e).

What do you see if you don't see any error? Do you see the address ranges being added correctly?

**Comment by kyeyoon-eeum** [comment]
ToT of `v0.4-dev` or ToT of `dgist-dev`.

Unbind fails with the following errors.
```
[SYS-SW] MemoryRange: base: 0x100030000000 size: 0x10000000, type: MEM_ADDR_TYPE.CXL_UNCACHED
[SYS-SW] MemoryRange: base: 0xFFFF888000000000 size: 0x1000000, type: MEM_ADDR_TYPE.DRAM
Host unbind notification root_port 0, device_vppb 0, val 0
[SYS-SW] Received Unbinding Root Port: 0, vPPB: 0 from FM
[SYS-SW] FM unbind device @ port: 0
[CxlHostPort0:CacheController] Removing MemoryRange addr: 0x60000000 addr_type: CFG
[CxlHostPort0:CacheController] Removing MemoryRange addr: 0xfe200000 addr_type: MMIO
[CxlHostPort0:CacheController] Removing MemoryRange addr: 0x100000000000 addr_type: CXL_UNCACHED
[CxlVirtualSwitch 0] Started unbinding physical port from vPPB 0
[DownstreamPortDevice:DSP1] Unbinding ld_id 0 to vPPB0 (noop)
VPPB unbinded from physical port, type: CXL_COMPONENT_TYPE.DSP
[CxlVirtualSwitch 0] Succcessfully unbound physical port from vPPB 0
[GetVirtualCxlSwitchInfoCommand] GetVirtualCxlSwitchInfoCommand error: 0, Traceback (most recent call last):
  File "/home/kyeyoon/eeum-dev/dgist/opencxl/cxl/component/cci_executor.py", line 63, in execute
    return await self._execute(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyeyoon/eeum-dev/dgist/opencxl/cxl/cci/fabric_manager/virtual_switch/get_virtual_cxl_switch_info.py", line 257, in _execute
    bound_ld_id = vcs.get_ld_id(vppb_id)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyeyoon/eeum-dev/dgist/opencxl/cxl/component/virtual_switch/virtual_switch.py", line 295, in get_ld_id
    return self._vppb_ld_id_map[vppb_id]
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 0

[GetVirtualCxlSwitchInfoCommand] GetVirtualCxlSwitchInfoCommand error: 0, Traceback (most recent call last):
  File "/home/kyeyoon/eeum-dev/dgist/opencxl/cxl/component/cci_executor.py", line 63, in execute
    return await self._execute(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyeyoon/eeum-dev/dgist/opencxl/cxl/cci/fabric_manager/virtual_switch/get_virtual_cxl_switch_info.py", line 257, in _execute
    bound_ld_id = vcs.get_ld_id(vppb_id)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyeyoon/eeum-dev/dgist/opencxl/cxl/component/virtual_switch/virtual_switch.py", line 295, in get_ld_id
    return self._vppb_ld_id_map[vppb_id]
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 0
```

**Comment by arter97** [comment]
Repro in CLI:

```
./cxl-util start -c fm -c switch -c sld-group -c host-group --config-file configs/1vcs_4sld.yaml
./cxl-util fm unbind 0 0
./cxl-util get-info vcs
```

**Comment by arter97** [comment]
https://github.com/opencxl/opencxl-core/pull/158
