### ISSUE TITLE
core: Crash when running 2vcs_8sld.yaml

### ISSUE THREAD

**Issue by kyeyoon-eeum** [opencxl/opencxl#136]
1. `./cxl-util start -c fm -c switch -c sld-group  -c host-group --config-file configs/2vcs_8sld.yaml`
2. Start UI tool
3. Crashes with the following errors.
```
[FabricManagerSocketIoServer] Received SocketIO Request: port:get, payload: None
[GetPhysicalPortStateCommand] GetPhysicalPortStateCommand error: list index out of range, Traceback (most recent call last):
  File "/home/kyeyoon/eeum-dev/my-opencxl-core/opencxl/cxl/component/cci_executor.py", line 63, in execute
    return await self._execute(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyeyoon/eeum-dev/my-opencxl-core/opencxl/cxl/cci/fabric_manager/physical_switch/get_physical_port_state.py", line 259, in _execute
    self._device_configs[port_info.port_id - 1], MultiLogicalDeviceConfig
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by arter97** [comment]
2. `./cxl-util get-info port` is also a reproducer

**Comment by arter97** [comment]
https://github.com/opencxl/opencxl-core/pull/163
